package ru.minesweeper.observer;

public enum Notifications {
    GAME_STARTED,
    HOST_STARTED,
    GAME_CHANGED,
    GAME_RUINED,
    GAME_WINED,

    TIME_UPDATED,

    RECORDS_UPDATED,

    SWAP_STARTED,
    SWAP_SUCCESS,

    LOBBY_NICKNAMES_UPDATED,
    HOST_DISCONNECTED,
    GAME_CHANGED_I_HOST,
    GAME_CHANGED_I_CLIENT,
    GAME_WINED_I_CLIENT,
    GAME_WINED_I_HOST,
    GAME_RUINED_I_CLIENT,
    GAME_RUINED_I_HOST,
}
